manifest:
  version: "1.2"

  self:
    path: manifest
    west-commands: scripts/west-commands.yml

  remotes:
    - name: origin
      url-base: https://github.com/JaagupAverin
  defaults:
    remote: origin
    revision: main

  # Disable all groups by default as everything is opt-in using `west config`
  # The `gale` group is only referenced by some custom west commands and indicates that the repository
  # contains user code (as opposed to third-party).
  group-filter: [-sensor, -hmi, -gale, -hal]
  projects:
    - name: gale-sensor-app
      path: sensor_app
      groups: [sensor, gale]
      west-commands: scripts/west-commands.yml

    - name: gale-hmi-app
      path: hmi_app
      groups: [hmi, gale]

    - name: gale-shared
      path: shared
      groups: [sensor, hmi, gale]

    - name: gale-zephyr
      path: zephyr
      west-commands: scripts/west-commands.yml
      groups: [sensor, hmi]

    - name: hal_espressif
      revision: dbc28ad4c1bdcdb25e79ca225cb5528a75d8dc91
      path: modules/hal/espressif
      west-commands: west/west-commands.yml
      groups: [sensor, hmi, hal]
