manifest:
  version: "1.2"

  self:
    path: manifest

  remotes:
    - name: origin
      url-base: https://github.com/JaagupAverin
  defaults:
    remote: origin
    revision: main

  projects:
    - name: gale-sensor-app
      path: sensor_app
    - name: gale-hmi-app
      path: hmi_app
    - name: gale-shared
      path: shared
      import: true
