manifest:
  version: "1.2"

  self:
    path: gale_manifest

  remotes:
    - name: origin
      url-base: https://github.com/JaagupAverin
  defaults:
    remote: origin
    revision: main

  projects:
    - name: gale-sensor-app
      path: gale_sensor_app
    - name: gale-hmi-app
      path: gale_hmi_app
    - name: gale-shared
      path: gale_shared
      import: true
